
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CTE DIV MULT PARA PARC RESTA SUMAexpression : expression SUMA termexpression : expression RESTA termexpression : termterm : term MULT factorterm : term DIV factorterm : factorfactor : CTEfactor : PARA expression PARC'
    
_lr_action_items = {'CTE':([0,5,6,7,8,9,],[4,4,4,4,4,4,]),'PARA':([0,5,6,7,8,9,],[5,5,5,5,5,5,]),'$end':([1,2,3,4,11,12,13,14,15,],[0,-3,-6,-7,-1,-2,-4,-5,-8,]),'SUMA':([1,2,3,4,10,11,12,13,14,15,],[6,-3,-6,-7,6,-1,-2,-4,-5,-8,]),'RESTA':([1,2,3,4,10,11,12,13,14,15,],[7,-3,-6,-7,7,-1,-2,-4,-5,-8,]),'PARC':([2,3,4,10,11,12,13,14,15,],[-3,-6,-7,15,-1,-2,-4,-5,-8,]),'MULT':([2,3,4,11,12,13,14,15,],[8,-6,-7,8,8,-4,-5,-8,]),'DIV':([2,3,4,11,12,13,14,15,],[9,-6,-7,9,9,-4,-5,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,],[1,10,]),'term':([0,5,6,7,],[2,2,11,12,]),'factor':([0,5,6,7,8,9,],[3,3,3,3,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression SUMA term','expression',3,'p_expression_suma','test_parser.py',39),
  ('expression -> expression RESTA term','expression',3,'p_expression_resta','test_parser.py',43),
  ('expression -> term','expression',1,'p_expression_term','test_parser.py',47),
  ('term -> term MULT factor','term',3,'p_term_mult','test_parser.py',51),
  ('term -> term DIV factor','term',3,'p_term_div','test_parser.py',55),
  ('term -> factor','term',1,'p_term_factor','test_parser.py',59),
  ('factor -> CTE','factor',1,'p_factor_cte','test_parser.py',63),
  ('factor -> PARA expression PARC','factor',3,'p_factor_expr','test_parser.py',67),
]
